name: Win64_Build

on:
  workflow_dispatch: # 手动点击运行

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Aria2 Win64
        run: |
          # 增加 --build-arg HOST=x86_64-w64-mingw32 来指定 64 位编译
          docker build --build-arg HOST=x86_64-w64-mingw32 -t aria2-builder -f Dockerfile.mingw .
          
          CONTAINER_ID=$(docker create aria2-builder)
          docker cp $CONTAINER_ID:/aria2/src/aria2c.exe ./aria2c.exe
          docker rm $CONTAINER_ID

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: aria2-custom-win64
          path: aria2c.exe
